# When set to "true", generated css files are minified.
minify_css = false

# When set to "true", generates draft pages as well.
include_drafts = false

# When set to "true", pretty-prints the JSON string in state.json.
pretty_print_state_cache = false